### ISSUE TITLE
hi 我自己翻译了一份

### ISSUE THREAD

**Issue by Guyao146** [CrispyXYZ/GeneticChickengineering-CN-RC30-Extended#5]
Hi 你好 我自己翻译了一份鸡因工程的描述 但是是简体中文的

鸡因工程是资源鸡的实现基础，其灵感来自于 SetyCz 流行的 Forge mod Chicken。
两者之间的主要区别在于，虽然鸡具有预先确定的鸡育种树
但鸡因工程使用非常基本的遗传学模拟来确定鸡的进展
这意味着你需要复习一下鸡的基因工程学 https://en.wikipedia.org/wiki/Punnett_square

插件基础与介绍
有关更多详细信息，请参阅 wiki https://github.com/kii-chan-reloaded/GeneticChickengineering/wiki
(PS 英文不行的，看下面，有我翻译的中文)
主世界的鸡大多数都是占主导地位的正常鸡，但是有些鸡具有潜在的力量。
这些鸡有了正确的工具、时间和充足的照顾，这些鸡的真正潜力也许能够被发掘出来
对鸡进行基因改良的第一步是制作鸡网并将一些鸡携带起来
接下来，构建一个基因测序仪来分析袖珍鸡并了解它的基因型
当您收集到两只或更多的正面基因鸡时，制作一个私人鸡舍并将您的鸡留给他们
一段时间后，他们将掷出基因骰子并生下一个带有这个随机基因的小鸡！
让它们长大成为一只真正的鸡，真正的可循环。
最终，你的努力将获得一只可以生产资源的特殊鸡！
但是，他们无法单独生鸡…… 这就是激发室有用的地方
插入具有至少一对纯合隐性等位基因（一组两个小写字母）的鸡，它将开始生产小鸡产生资源
不过，并非所有基因类型的鸡都会以相同的速度生产资源。
由于杂合等位基因对（一个显性和一个隐性）的干扰
只有纯合对的鸡比具有杂合基因的鸡更快地获得资源
将一些货物节点添加到激发室，以保持稳定、永无止境的不同资源供应！
查看序列表或游戏内的 Slimefun 指南以了解如何制作特定资源
或者开始疯狂饲养鸡，直到拥有所有 64 个品种！

**Comment by CrispyXYZ** [comment]
已写入README.md 见 0545ae3
